const City = require('../models/cityModel');

const defaultCities = [
  {
    name: '東京',
    englishName: 'Tokyo',
    country: '日本',
    englishCountryName: 'Japan',
    isVisible: true,
    timezone: 'Asia/Tokyo',
    timezoneOffset: 9,
  },
  {
    name: '首爾',
    englishName: 'Seoul',
    country: '韓國',
    englishCountryName: 'South Korea',
    isVisible: true,
    timezone: 'Asia/Seoul',
    timezoneOffset: 9,
  },
  {
    name: '台北',
    englishName: 'Taipei',
    country: '台灣',
    englishCountryName: 'Taiwan',
    isVisible: true,
    timezone: 'Asia/Taipei',
    timezoneOffset: 8,
  },
  {
    name: '香港',
    englishName: 'Hong Kong',
    country: '中國香港',
    englishCountryName: 'Hong Kong',
    isVisible: true,
    timezone: 'Asia/Hong_Kong',
    timezoneOffset: 8,
  },
  {
    name: '北京',
    englishName: 'Beijing',
    country: '中國',
    englishCountryName: 'China',
    isVisible: true,
    timezone: 'Asia/Shanghai',
    timezoneOffset: 8,
  },
  {
    name: '新加坡',
    englishName: 'Singapore',
    country: '新加坡',
    englishCountryName: 'Singapore',
    isVisible: true,
    timezone: 'Asia/Singapore',
    timezoneOffset: 8,
  },
  {
    name: '曼谷',
    englishName: 'Bangkok',
    country: '泰國',
    englishCountryName: 'Thailand',
    isVisible: true,
    timezone: 'Asia/Bangkok',
    timezoneOffset: 7,
  },
  {
    name: '雅加達',
    englishName: 'Jakarta',
    country: '印尼',
    englishCountryName: 'Indonesia',
    isVisible: true,
    timezone: 'Asia/Jakarta',
    timezoneOffset: 7,
  },
  {
    name: '德里',
    englishName: 'New Delhi',
    country: '印度',
    englishCountryName: 'India',
    isVisible: true,
    timezone: 'Asia/Kolkata',
    timezoneOffset: 5.5,
  },

  {
    name: '倫敦',
    englishName: 'London',
    country: '英國',
    englishCountryName: 'United Kingdom',
    isVisible: true,
    timezone: 'Europe/London',
    timezoneOffset: 0,
  },
  {
    name: '巴黎',
    englishName: 'Paris',
    country: '法國',
    englishCountryName: 'France',
    timezone: 'Europe/Paris',
    timezoneOffset: 1,
  },
  {
    name: '柏林',
    englishName: 'Berlin',
    country: '德國',
    englishCountryName: 'Germany',
    timezone: 'Europe/Berlin',
    timezoneOffset: 1,
  },
  {
    name: '馬德里',
    englishName: 'Madrid',
    country: '西班牙',
    englishCountryName: 'Spain',
    timezone: 'Europe/Madrid',
    timezoneOffset: 1,
  },
  {
    name: '羅馬',
    englishName: 'Rome',
    country: '義大利',
    englishCountryName: 'Italy',
    timezone: 'Europe/Rome',
    timezoneOffset: 1,
  },
  {
    name: '莫斯科',
    englishName: 'Moscow',
    country: '俄羅斯',
    englishCountryName: 'Russia',
    timezone: 'Europe/Moscow',
    timezoneOffset: 3,
  },

  {
    name: '紐約',
    englishName: 'New York',
    country: '美國',
    englishCountryName: 'United States',
    timezone: 'America/New_York',
    timezoneOffset: -5,
  },
  {
    name: '芝加哥',
    englishName: 'Chicago',
    country: '美國',
    englishCountryName: 'United States',
    timezone: 'America/Chicago',
    timezoneOffset: -6,
  },
  {
    name: '丹佛',
    englishName: 'Denver',
    country: '美國',
    englishCountryName: 'United States',
    timezone: 'America/Denver',
    timezoneOffset: -7,
  },
  {
    name: '洛杉磯',
    englishName: 'Los Angeles',
    country: '美國',
    englishCountryName: 'United States',
    timezone: 'America/Los_Angeles',
    timezoneOffset: -8,
  },
  {
    name: '多倫多',
    englishName: 'Toronto',
    country: '加拿大',
    englishCountryName: 'Canada',
    timezone: 'America/Toronto',
    timezoneOffset: -5,
  },
  {
    name: '溫哥華',
    englishName: 'Vancouver',
    country: '加拿大',
    englishCountryName: 'Canada',
    timezone: 'America/Vancouver',
    timezoneOffset: -8,
  },

  {
    name: '聖保羅',
    englishName: 'São Paulo',
    country: '巴西',
    englishCountryName: 'Brazil',
    timezone: 'America/Sao_Paulo',
    timezoneOffset: -3,
  },
  {
    name: '布宜諾斯艾利斯',
    englishName: 'Buenos Aires',
    country: '阿根廷',
    englishCountryName: 'Argentina',
    timezone: 'America/Argentina/Buenos_Aires',
    timezoneOffset: -3,
  },

  {
    name: '雪梨',
    englishName: 'Sydney',
    country: '澳洲',
    englishCountryName: 'Australia',
    timezone: 'Australia/Sydney',
    timezoneOffset: 10,
  },
  {
    name: '墨爾本',
    englishName: 'Melbourne',
    country: '澳洲',
    englishCountryName: 'Australia',
    timezone: 'Australia/Melbourne',
    timezoneOffset: 10,
  },
  {
    name: '奧克蘭',
    englishName: 'Auckland',
    country: '紐西蘭',
    englishCountryName: 'New Zealand',
    timezone: 'Pacific/Auckland',
    timezoneOffset: 12,
  },

  {
    name: '開羅',
    englishName: 'Cairo',
    country: '埃及',
    englishCountryName: 'Egypt',
    timezone: 'Africa/Cairo',
    timezoneOffset: 2,
  },
  {
    name: '約翰尼斯堡',
    englishName: 'Johannesburg',
    country: '南非',
    englishCountryName: 'South Africa',
    timezone: 'Africa/Johannesburg',
    timezoneOffset: 2,
  },
  {
    name: '奈洛比',
    englishName: 'Nairobi',
    country: '肯亞',
    englishCountryName: 'Kenya',
    timezone: 'Africa/Nairobi',
    timezoneOffset: 3,
  },
];

exports.getDefaultCities = async (userId) => {
  const citiesWithUser = defaultCities.map((city) => ({
    ...city,
    userId,
  }));

  await City.insertMany(citiesWithUser);
};
